name: Sync to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Optional: Remove files you don't want on HF (keep README.md)
      - name: Remove unnecessary files
        run: rm -rf .git .github .gitignore

      - name: Sync to Hugging Face Spaces
        uses: JacobLinCool/huggingface-sync@v1
        with:
          github: ${{ secrets.GITHUB_TOKEN }}
          user: Amy07amitha           # your Hugging Face username
          space: Attendance_Tracker   # your Hugging Face Space name
          token: ${{ secrets.HF_TOKEN }}
